services:
  mongo
    image: mongo
    port:
    -27107:27107
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: querty
      
  mongo-express
    image: mongo-express
    port:
    -8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: querty
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27107/    