services:
  mongo:
    image: mongo
    ports:
    - 27107:27107
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: querty

  mongo-express:
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: querty
      ME_CONFIG_MONGODB_URL: mongodb://admin:querty@mongo:27107/    